audit_header: false
title: '#1 Wireless Infrastructure Recruiter'
description: "Is your company, business, or career being hamstrung by not having access to the best talent in the industry? Are you tired of wasting time interviewing candidates who are not a dead-on fit for your critical and urgent hiring needs?\n\nAt GRN Blackhawk we specialize in the Telecom Infrastructure space (Wireless & Wireline). We are Headhunters - we extract Rock Stars from your competitors who are NOT looking for a job and give you the opportunity to sell them on your business. These individuals can make a huge and immediate impact to your bottom line.\n\nWe partner with CEOs, Presidents, Board members and Private Equity firms to help build their companies by recruiting C-Level talent, as well as Vice Presidents and Directors of Sales, Operations, Engineering, Marketing, Supply Chain, Product Management, IT, etc. \n\nPaul is a successful Executive-level professional with 30+ years experience in Telecom. As the #1 most connected recruiter in this industry he is able to recruit key individuals with the specific background, experience, skill set, and DNA required. This results in long-term strategic alliances with clients and candidates alike. They are assured of a discrete and respectful manner as well as total and complete confidentiality.\n\nOur expertise includes; Wireless, Wireline, New Site Builds, Macro Towers, Small Cell/DAS, fiber, Wi-Fi, Microwave, RF Engineering, 4G/LTE, 5G, In-Building Wireless (IBW), CBRS, OSP/Outside Plant, Smart Cities, IoT, SDN/NFV, Big Data, Cloud, Data Centers, Connected Cars / Autonomous Vehicles, TeleHealth, M&A, etc. \n\nSample clients served: AT&T, Verizon, T-Mobile, Sprint, FirstNet, Ericsson, Nokia / Alcatel-Lucent, Samsung, Huawei, ZTE, Tower companies, turfing vendors, manufacturers, neutral hosts, etc.\n\nWith almost 200 offices GRN has been recognized as:\n•\tForbes - Top 20 Executive Search Firms in 2018\n•\tEntrepreneur Magazine - Prestigious Franchise 500®\n•\tINC Magazine “Fastest-Growing Private Companies in America” three years in a rowss time."
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Paul Harris and Steve Bond
  title: Executive Recruiters
  license_number:
  about_markdown: >-
    At GRN Blackhawk our passion lies in building companies in the Wireless
    Infrastructure space. Engaging cutting edge initiatives that address the
    mobile industry (and of mobile operators in particular). These undertakings
    span across several key areas including Construction and Engineering (C&E),
    Spectrum, Smart Cities, The Autonomous Car, Connected Living, IoT, Personal
    Data, Digital Commerce, Telehealth, and more.


    Clients benefit from GRN's focus in Wireless and vast experience in Sales,
    Engineering, Operations, IT, Marketing, etc. GRN Blackhawk leverages years
    of experience and extensive industry contacts to recruit key individuals
    with the specific background, experience and skill set that clients require.
    This enables clients to gain access to highly qualified people that they
    would never have access to otherwise.
  market: San Ramon
  brand: GRN of Blackhawk
  brokerage:
  address: '2430 Camino Ramon ste #104<br>San Ramon, CA.'
  phone: (925) 804-6211
  phone_type:
  phone2:
  phone2_type:
  email: pharris@grnblackhawk.com
  email_type: Paul
  email2: sbond@grnblackhawk.com
  email2_type: Steve
  url: 'http://blackhawk-recruiters.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Looking to Build Your Career?
    CTA_text: >-
      Let's talk about how GRN of Blackhawk can take your business to new
      heights.
    CTA_link_text: Free Strategy Session
    CTA_url: /contact/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/grnblackhawk/'
  linkedin_url: 'https://www.linkedin.com/company/global-recruiters-of-blackhawk-grn'
  youtube_url: 'https://www.youtube.com/channel/UC3220MlgApuvq1P4ZZRxDBA'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: San Ramon Real Estate Podcast with Paul Harris and Steve Bond
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the San Ramon
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from GRN of Blackhawk - your professional
    San Ramon Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in San Ramon, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Paul Harris and Steve Bond
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: San Ramon Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#75a8a1'
  theme_color: '#48788c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'