audit_header: false
title: San Ramon's Best Real Estate Training
description: >-
  Paul Harris and Steve Bond, a top Real Estate Agent in San Ramon, shares their
  own internal real estate agent training for free. Their Real Estate Training,
  Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Paul Harris and Steve Bond
  title: Executive Recruiters
  license_number:
  about_markdown: >-
    At GRN Blackhawk our passion lies in building companies in the Wireless
    Infrastructure space. Engaging cutting edge initiatives that address the
    mobile industry (and of mobile operators in particular). These undertakings
    span across several key areas including Construction and Engineering (C&E),
    Spectrum, Smart Cities, The Autonomous Car, Connected Living, IoT, Personal
    Data, Digital Commerce, Telehealth, and more.


    Clients benefit from GRN's focus in Wireless and vast experience in Sales,
    Engineering, Operations, IT, Marketing, etc. GRN Blackhawk leverages years
    of experience and extensive industry contacts to recruit key individuals
    with the specific background, experience and skill set that clients require.
    This enables clients to gain access to highly qualified people that they
    would never have access to otherwise.
  market: San Ramon
  brand: GRN of Blackhawk
  brokerage:
  address: '2430 Camino Ramon ste #104<br>San Ramon, CA.'
  phone: (925) 804-6211
  phone_type:
  phone2:
  phone2_type:
  email: pharris@grnblackhawk.com
  email_type: Paul
  email2: sbond@grnblackhawk.com
  email2_type: Steve
  url: 'http://blackhawk-recruiters.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Looking to Build Your Career?
    CTA_text: >-
      Let's talk about how GRN of Blackhawk can take your business to new
      heights.
    CTA_link_text: Free Strategy Session
    CTA_url: /contact/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/grnblackhawk/'
  linkedin_url: 'https://www.linkedin.com/company/global-recruiters-of-blackhawk-grn'
  youtube_url: 'https://www.youtube.com/channel/UC3220MlgApuvq1P4ZZRxDBA'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: San Ramon Real Estate Podcast with Paul Harris and Steve Bond
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the San Ramon
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from GRN of Blackhawk - your professional
    San Ramon Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in San Ramon, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Paul Harris and Steve Bond
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: San Ramon Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#75a8a1'
  theme_color: '#48788c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'